#!/usr/bin/env bash

set -e

if [ ! -f install ]; then
    echo 'install must be run within its container folder' 1>&2
    exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$GOPATH:$CURDIR"

if [ ! -d log ]; then
    mkdir log
fi

go get -u github.com/go-sql-driver/mysql
go get -u github.com/gorilla/mux
go get -u github.com/gorilla/securecookie
go get -u github.com/astaxie/beego/cache

gofmt -w src

go install gocollipa

export GOPATH="$OLDGOPATH"

echo 'finished'
